# Reusable locale tasks for ManageIQ plugins
# Plugins can use these by calling Vmdb::PluginLocaleTasks methods

module Vmdb
  module PluginLocaleTasks
    class << self
      # Extract translatable strings from plugin code
      # This method should be called from within a rake task that has already
      # defined the gettext helper methods (locale_path, files_to_translate, text_domain)
      # in a 'namespace :gettext' block.
      # @param plugin_name [String] The plugin name (e.g., 'my_plugin')
      # @param plugin_root [Pathname] The plugin's root directory
      # @param domain [String] Optional text domain (defaults to plugin_name)
      def extract_strings(plugin_name, plugin_root, domain: nil)
        domain ||= plugin_name
        locale_path = plugin_root.join('locale')

        # Create locale directory if it doesn't exist
        FileUtils.mkdir_p(locale_path.join('en'))

        # Configure gettext for this plugin
        FastGettext.add_text_domain(domain,
                                    :path           => locale_path.to_s,
                                    :type           => :po,
                                    :ignore_fuzzy   => true,
                                    :report_warning => false)

        puts "Extracting strings for #{domain}..."

        # Invoke gettext:find task
        # In a plugin/engine context, the task is namespaced under 'app:'
        task_name = defined?(ENGINE_ROOT) ? 'app:gettext:find' : 'gettext:find'
        Rake::Task[task_name].reenable
        Rake::Task[task_name].invoke

        puts "Generated #{locale_path.join("#{domain}.pot")}"
        puts "Generated #{locale_path.join('en', "#{domain}.po")}"
      end

      # Convert PO files to JSON for JavaScript consumption
      # @param plugin_name [String] The plugin name (e.g., 'my_plugin')
      # @param plugin_root [Pathname] The plugin's root directory
      def po_to_json(plugin_name, plugin_root)
        require 'po_to_json'

        po_dir = plugin_root.join('locale')
        # Use oldjs/locale to match ui-classic structure
        json_dir = plugin_root.join('app/javascript/oldjs/locale')

        json_dir.mkpath

        # Convert each locale's PO file to JSON
        # Only process main domain PO files, skip .edit.po and other temporary files
        Dir.glob(po_dir.join('*/*.po')).each do |po_file|
          # Skip temporary/edit files
          next if po_file.end_with?('.edit.po')

          locale = File.basename(File.dirname(po_file))
          json_file = json_dir.join("#{locale}.json")

          po2json = PoToJson.new(po_file)
          # Use generate_for_json to get pure JSON (not wrapped in JavaScript)
          json_content = po2json.generate_for_json(locale, :pretty => true)

          File.write(json_file, json_content)
          puts "Generated #{json_file}"
        end

        # Generate index.js for webpack
        generate_webpack_index(plugin_name, json_dir)
      end


      def generate_webpack_index(plugin_name, json_dir)
        index_file = json_dir.join('index.js')
        locales = Dir.glob(json_dir.join('*.json')).map { |f| File.basename(f, '.json') }.sort

        index_content = <<~JS
          // Auto-generated by Vmdb::PluginLocaleTasks.po_to_json
          // Plugin locale data for #{plugin_name}
          window.pluginLocales = window.pluginLocales || {};
          window.pluginLocales['#{plugin_name}'] = {
          #{locales.map { |l| "  '#{l}': require('./#{l}.json')," }.join("\n")}
          };
        JS

        File.write(index_file, index_content)
        puts "Generated #{index_file}"
      end
    end
  end
end
